[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DifferentialEvolutionMetropolis = "a5908a69-3cf8-4221-8182-38852cbc47b2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"

[sources]
DifferentialEvolutionMetropolis = {path = "./.."}
