repos:
  - repo: https://github.com/fredrikekre/runic-pre-commit
    rev: v2.0.1
    hooks:
      - id: runic
  - repo: https://github.com/JuliaTesting/ExplicitImports.jl
    rev: v1.10.0
    hooks:
      - id: explicit-imports
        args: [--print,--checklist,"exclude_all_qualified_accesses_are_public"]